---
# Default settings for vms
vm:
  memory: 512
  cpu: 1
  role: ostest
  puppet_apply: false
  puppet_agent: false
  facter_external_facts: false
  facter_trusted_facts: false

network:
  range: 10.42.40.0/24
  ip_start_offset: 101
  domain: bare

# Vagrant settings
vagrant:
  # Update host's /etc/hosts if you have the hostmanager plugin.
  # Needed for automatic decommissioning of nodes. If false, you've to manage
  # manually ssl certs removal of reinstalled nodes.
  hostmanager.manage_host: false # If true and you have the hostmanager plugin

puppet:
  version: latest
  env: devel
  zone: vagrant
  setup: false

vbguest:
  auto_update: true

# Nodes shown in vagrant status 
nodes:
  - hostname_base: centos7
    box: centos7
  - hostname_base: centos6
    box: centos6
  - hostname_base: ubuntu1604
    box: ubuntu1604 
  - hostname_base: ubuntu1404
    box: ubuntu1404 
  - hostname_base: ubuntu1204
    box: ubuntu1204 
  - hostname_base: debian8
    box: debian8
  - hostname_base: debian7
    box: debian7
  - hostname_base: suse12
    box: suse12
  - hostname_base: suse11
    box: suse11
  - hostname_base: alpine3
    box: alpine3
  - hostname_base: fedora25
    box: fedora25
  - hostname_base: fedora24
    box: fedora24
  - hostname_base: fedora23
    box: fedora23
  - hostname_base: windows2012
    box: windows2012
  - hostname_base: windows2008
    box: windows2008
  - hostname_base: solaris11
    box: solaris11
  - hostname_base: solaris10
    box: solaris10
  - hostname_base: freebsd12
    box: freebsd12
  - hostname_base: freebsd11
    box: freebsd11
  - hostname_base: freebsd10
    box: freebsd10
  - hostname_base: osx1011
    box: osx1011
    vagrant_mount: false
  - hostname_base: osx1010
    box: osx1010
    vagrant_mount: false


boxes:
  centos7:
    box: centos/7
    breed: redhat7
  centos6:
    box: centos/6
    breed: redhat6
  centos7_puppet:
    box: puppetlabs/centos-7.2-64-puppet
    breed: puppetlabs-centos7
  centos6_puppet:
    box: puppetlabs/centos-6.6-64-puppet
    breed: puppetlabs
  ubuntu1604:
    box: ubuntu/xenial64
    breed: ubuntu
  ubuntu1404:
    box: ubuntu/trusty64
    breed: ubuntu
  ubuntu1204:
    box: ubuntu/precise64
    breed: ubuntu
  ubuntu1604_puppet:
    box: puppetlabs/ubuntu-16.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1404_puppet:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1204_puppet:
    box: puppetlabs/ubuntu-12.04-64-puppet
    breed: puppetlabs-ubuntu1204
  debian8:
    box: debian/jessie64
    breed: debian
  debian7:
    box: debian/wheezy64
    breed: debian
  debian8_puppet:
    box: puppetlabs/debian-8.2-64-puppet
    breed: puppetlabs-apt
  debian7_puppet:
    box: puppetlabs/debian-7.8-64-puppet
    breed: puppetlabs-apt
  debian6_puppet:
    box: puppetlabs/debian-6.0.10-64-puppet
    breed: puppetlabs-apt
  alpine3:
    box: maier/alpine-3.3.1-x86_64
    breed: alpine
  fedora23:
    box: fedora/23-cloud-base
    breed: redhat7
  fedora24:
    box: fedora/24-cloud-base
    breed: redhat7
  fedora25:
    box: fedora/25-cloud-base
    breed: redhat7
  windows2008:
    box: opentable/win-2008r2-standard-amd64-nocm
    breed: win2008
  windows2012:
    box: opentable/win-2012r2-standard-amd64-nocm
    breed: win2012
  solaris10:
    box: tnarik/solaris10-minimal
    breed: solaris10
  solaris11:
    box: ruby-concurrency/oracle-solaris-11
    breed: solaris11
  freebsd10:
    box: freebsd/FreeBSD-10.2-RELEASE
    breed: freebsd
  freebsd11:
    box: freebsd/FreeBSD-11.0-RELEASE
    breed: freebsd
  freebsd12:
    box: freebsd/FreeBSD-12.0-RELEASE
    breed: freebsd
  osx1010:
    box: dhoer/macosx-10.10
    breed: macos
  osx1011:
    box: carbon/osx-elcapitan-10.11
    breed: macos

# Image available for suse12 has issues. To setup correctly:
# vagrant up suse12
# vagrant provision suse12
# vagrant reload suse12
# vagrant provision suse12
  suse12:
    box: suse/sles12sp1
    breed: suse12
  suse11:
    box: suse/sles11sp3
    breed: suse11

