# GitLab CI configuration
# Example for public Gitlab workflow
#
stages:
  - checks
  - specs
  - diffs
  - integration
  - live_runs
  - merge_request
  - promote
  - rollout
  - postcheck


# Development branch
syntax:
  stage: checks
  before_script:
    - "bin/gitlab_before.sh"
  script: "bin/puppet_check_syntax_fast.sh"
  cache:
    untracked: true
    paths:
    - modules/
  tags:
    - linux
    - test_puppet
  only:
    - development
  environment:
    name: development
    url: https://development.example.com

lint:
  stage: checks
  before_script:
    - "bin/gitlab_before.sh"
  script: "bin/puppet_lint.sh"
  cache:
    untracked: true
    paths:
    - modules/
  tags:
    - linux
    - test_puppet
  only:
    - development
  allow_failure: true

rake_site:
  stage: specs
  before_script:
    - "bin/gitlab_before.sh"
  script: "bin/puppet_check_rake.sh site"
  cache:
    untracked: true
    paths:
    - modules/
  tags:
    - linux
    - test_puppet
  only:
    - development
  allow_failure: true

rake_modules:
  stage: specs
  before_script:
    - "bin/gitlab_before.sh"
  script: "bin/puppet_check_rake.sh modules"
  cache:
    untracked: true
    paths:
    - modules/
  tags:
    - linux
    - test_puppet
  only:
    - development
  allow_failure: true

