---
# Default settings for vms
vm:
  memory: 512
  cpu: 1
  role: ostest
  puppet_apply: true
  puppet_agent: false

network:
  range: 10.42.43.0/24
  ip_start_offset: 101
  domain: devel

puppet:
  version: latest
  env: test
  zone: local

# Nodes shown in vagrant status 
nodes:
  - hostname_base: centos7
    box: centos7
  - hostname_base: centos6
    box: centos6
  - hostname_base: ubuntu1604
    box: ubuntu1604 
  - hostname_base: ubuntu1404
    box: ubuntu1404 
  - hostname_base: ubuntu1204
    box: ubuntu1204 
  - hostname_base: debian8
    box: debian8
  - hostname_base: debian7
    box: debian7
  - hostname_base: alpine3
    box: alpine3
  - hostname_base: fedora23
    box: fedora23
  - hostname_base: suse12
    box: suse12


boxes:
  centos7:
    box: puppetlabs/centos-7.2-64-puppet
    breed: puppetlabs-centos7
  centos7_puppet3:
    box: webhippie/centos-7
    breed: redhat7
  centos6:
    box: puppetlabs/centos-6.6-64-puppet
    breed: puppetlabs
  ubuntu1604:
    box: puppetlabs/ubuntu-16.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1404:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1204:
    box: puppetlabs/ubuntu-12.04-64-puppet
    breed: puppetlabs-ubuntu1204
  debian8:
    box: puppetlabs/debian-8.2-64-puppet
    breed: puppetlabs-apt
  debian7:
    box: puppetlabs/debian-7.8-64-puppet
    breed: puppetlabs-apt
  debian6:
    box: puppetlabs/debian-6.0.10-64-puppet
    breed: puppetlabs-apt
  alpine3:
    box: maier/alpine-3.3.1-x86_64
    breed: alpine
  fedora23:
    box: fedora/23-cloud-base
    breed: redhat7
  suse12:
    box: bheegu1/sles-12-sp1
    breed: suse12
# Image used for suse12 has issues. To setup correctly:
# vagrant up suse12
# vagrant provision suse12
# vagrant reload suse12
# vagrant provision suse12
