---
# Default settings for vms
vm:
  memory: 512
  cpu: 1
  role: ostest
  puppet_apply: true
  puppet_agent: false
  facter_external_facts: true
  facter_trusted_facts: false

network:
  range: 10.42.43.0/24
  ip_start_offset: 101
  domain: devel

puppet:
  version: latest
  env: devel
  zone: vagrant

# Nodes shown in vagrant status 
nodes:
  - hostname_base: centos7
    box: centos7
  - hostname_base: centos6
    box: centos6
  - hostname_base: ubuntu1604
    box: ubuntu1604 
  - hostname_base: ubuntu1404
    box: ubuntu1404 
  - hostname_base: ubuntu1204
    box: ubuntu1204 
  - hostname_base: debian8
    box: debian8
  - hostname_base: debian7
    box: debian7
  - hostname_base: suse12
    box: suse12
  - hostname_base: suse11
    box: suse11
  - hostname_base: opensuse-tumbleweed
    box: opensuse_tumbleweed
  - hostname_base: opensuse-42-1
    box: opensuse_42_1
  - hostname_base: alpine3
    box: alpine3
  - hostname_base: fedora23
    box: fedora23
  - hostname_base: cumulus
    box: cumulus



boxes:
  centos7:
    box: centos/7
    breed: redhat7
  centos6:
    box: centos/6
    breed: redhat6
  centos7_puppet:
    box: puppetlabs/centos-7.2-64-puppet
    breed: puppetlabs-centos7
  centos6_puppet:
    box: puppetlabs/centos-6.6-64-puppet
    breed: puppetlabs
  ubuntu1604:
    box: ubuntu/xenial64
    breed: ubuntu
  ubuntu1404:
    box: ubuntu/trusty64
    breed: ubuntu
  ubuntu1204:
    box: ubuntu/precise64
    breed: ubuntu
  ubuntu1604_puppet:
    box: puppetlabs/ubuntu-16.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1404_puppet:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1204_puppet:
    box: puppetlabs/ubuntu-12.04-64-puppet
    breed: puppetlabs-ubuntu1204
  debian8:
    box: debian/jessie64
    breed: debian
  debian7:
    box: debian/wheezy64
    breed: debian
  debian8_puppet:
    box: puppetlabs/debian-8.2-64-puppet
    breed: puppetlabs-apt
  debian7_puppet:
    box: puppetlabs/debian-7.8-64-puppet
    breed: puppetlabs-apt
  debian6_puppet:
    box: puppetlabs/debian-6.0.10-64-puppet
    breed: puppetlabs-apt
  alpine3:
    box: maier/alpine-3.3.1-x86_64
    breed: alpine
  fedora23:
    box: fedora/23-cloud-base
    breed: redhat7
  cumulus:
    box: CumulusCommunity/cumulus-vx
    breed: puppetlabs-apt


# Image available for suse12 has issues. To setup correctly:
# vagrant up suse12
# vagrant provision suse12
# vagrant reload suse12
# vagrant provision suse12
  suse12:
    box: suse/sles12sp1
    breed: suse12
  suse11:
    box: suse/sles11sp3
    breed: suse11
  opensuse_tumbleweed:
    box: opensuse/openSUSE-Tumbleweed-x86_64
    breed: none 
  opensuse_42_1:
    box: opensuse/openSUSE-42.1-x86_64
    breed: none 



