---
  profiles:
    - '::profile::mongo'

  profile::mongo::replset: 'configReplSet'
  profile::mongo::tp::options:
    port: '27019'
    journal_enabled: true
    sharding: 'clusterRole'
    
  profile::mongo::replset_members:
    - '%{::zone}-mongoconfig-1-%{::env}-01:27019'
    - '%{::zone}-mongoconfig-2-%{::env}-01:27019'
    - '%{::zone}-mongoconfig-3-%{::env}-01:27019'
