---
# Default settings for vms
vm:
  memory: 1024
  cpu: 1
  box: centos7 # From boxes list below
  puppet_apply: true
  puppet_agent: false

network:
  range: 10.42.42.0/24
  ip_start_offset: 101
  domain: example42.dev

puppet:
  version: latest
  env: dev
  zone: local
  master_ip: 10.42.42.10
  master_hostname: dev-local-puppet-01

# Nodes shown in vagrant status 
nodes:
  - role: tpweb
    count: 1
    memory: 2048
  - role: log
    count: 1
  - role: mon
    count: 1
  - role: aws
    count: 1
  - role: docker_build
    hostname_base: docker-build
    count: 1
    box: ubuntu1404
  - role: docker_host
    hostname_base: docker-host
    count: 1
    box: ubuntu1404
  - role: puppet
    count: 1
    memory: 4096
    cpu: 2
    box: ubuntu1604
    ip_address: 10.42.42.10
    puppet_apply: true
    aliases:
      - puppet
  - role: puppetdb
    count: 1
    puppet_apply: true

boxes:
  centos7:
    box: puppetlabs/centos-7.2-64-puppet
    breed: puppetlabs-centos7
  centos7_puppet3:
    box: webhippie/centos-7
    breed: redhat7
  centos7_pe:
    box: puppetlabs/centos-7.0-64-puppet-enterprise
    breed: puppetlabs
  centos6:
    box: puppetlabs/centos-6.6-64-puppet
    breed: puppetlabs
  ubuntu1604:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1404:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1204:
    box: puppetlabs/ubuntu-12.04-64-puppet
    breed: puppetlabs-ubuntu1204
  debian8:
    box: puppetlabs/debian-8.2-64-puppet
    breed: puppetlabs-apt
  debian7:
    box: puppetlabs/debian-7.8-64-puppet
    breed: puppetlabs-apt
  debian6:
    box: puppetlabs/debian-6.0.10-64-puppet
    breed: puppetlabs-apt

